module.exports = {
  DREQ_PARTICIPANTS: {
    PROVIDER: 'PROVIDER',
    REQUESTER: 'REQUESTER',
    ADMIN: 'ADMIN',
  },
  DREQ_STATE: {
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETE: 'COMPLETE',
    CANCELED: 'CANCELED',
  },
  DOC_STATE: {
    REQUESTED: 'REQUESTED',
    UPLOADED: 'UPLOADED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    NOT_REQUIRED: 'NOT_REQUIRED',
  },
  REMINDER_TYPES: {
    ONE_DAY: 'ONE_DAY',
    THREE_DAYS: 'THREE_DAYS',
    ONE_WEEK: 'ONE_WEEK',
    MANUALLY: 'MANUALLY',
  },
};
